astarte-platform/astarte-dashboard

- src/elm/Modal/NewAlias.elm
> NewAlias: use title case in modal title

- CHANGELOG.md
- package-lock.json
- package.json
Bump all version numbers and update CHANGELOG.md.
> Prepare 0.11.0-beta.1 release

- CHANGELOG.md
- package-lock.json
- package.json
> Prepare 0.11.0-beta.2

- CHANGELOG.md
- src/elm/Types/DeviceData.elm
Property values are not wrapped in a "value" field
Fix #12
> DeviceData: add property value conversion

- src/elm/Page/Interfaces.elm
- src/elm/Page/Triggers.elm
Use list groups instead of accordions
> Interfaces and triggers list restyle

- src/elm/Page/Device.elm
Hide device %stats columns in low resolution screens
> Device.elm: fix device stats table responsiveness

- CHANGELOG.md
- package-lock.json
- package.json
Prepare first 0.11.0 release candidate.
> Prepare 0.11.0-rc.0

- package-lock.json
Update to latest babel to fix a bug that prevented
the dashboard from starting
See https://github.com/babel/babel/issues/11216
> Fix babel and node 13.10.1 interaction

- CHANGELOG.md
- src/elm/AstarteApi.elm
- src/elm/Page/Device.elm
Allow users to wipe device credentials from Astarte
pairing agent.
> Add wipe device credentials functionality

- CHANGELOG.md
- package-lock.json
- package.json
Update version number and changelog date.
> Prepare v0.11.0-rc.1 release

- CHANGELOG.md
- package-lock.json
- package.json
Update changelog and version numbers.
> Prepare 0.11.0

- CHANGELOG.md
- src/elm/AstarteApi.elm
- src/elm/Page/Device.elm
Display error messages to the user when not being able to
retrieve device infos
> Handle device info errors

- src/elm/Main.elm
Apply the same navbar style to the editr editor-only navbar
> Main.elm: editor-only navbar colors

- CHANGELOG.md
- src/elm/AstarteApi.elm
- src/elm/Main.elm
Show Pairing API health status in the navbar
> Add Pairing API health check

- CHANGELOG.md
- src/elm/AstarteApi.elm
- src/elm/Icons.elm
- src/elm/Modal/AskKeyValue.elm
- src/elm/Modal/AskSingleValue.elm
- src/elm/Modal/ConfirmModal.elm
- src/elm/Modal/NewMetadata.elm
- src/elm/Page/Device.elm
- src/elm/Types/Device.elm
- src/static/styles/main.scss
Show device metadata in the device page and edit them with a modal
> Aliases and metadata editing

- src/react/DevicesPage.js
> DevicesPage: Always show device registration link

- src/react/Base64.js
- src/react/RegisterDevicePage.js
Allow users to generate device IDs using UUIDv5
> RegisterDevicePage: add UUIDv5 option

- src/react/RegisterDevicePage.js
Return to the device list page after confirming the device secret
> RegisterDevicePage: return to device list after registration

- package-lock.json
- package.json
- src/react/AstarteClient.js
As of Feb 11th 2020, the library "request" is fully deprecated.
For this reason, switch to axios library
> Replace request-promise with axios

- src/elm/Page/InterfaceBuilder.elm
- src/static/styles/main.scss
- Title rows always take the full width of the container
- Fixed title case mismatch
- Uniform "Add new..." buttons with the visual representation
of added items
> InterfaceBuilder: minor style adjustments

- src/static/styles/main.scss
> Remove validation succesful icon 

- CHANGELOG.md
- src/elm/Page/TriggerBuilder.elm
> TriggerBuilder: allow placeholders in data trigger paths

- src/elm/Page/Home.elm
> Home.elm: Add pairing API health icon

- src/elm/Page/InterfaceBuilder.elm
- src/elm/Types/InterfaceMapping.elm
Show mapping types as badge before the mapping endpoint
> InterfaceBuilder: mapping type as badge

- src/react/AstarteClient.js
- src/react/DevicesPage.js
- src/react/GroupDevicesPage.js
- src/react/GroupsPage.js
- src/react/NewGroupPage.js
- src/react/RegisterDevicePage.js
- src/react/Router.js
- src/static/index.js
- Init the Astarte client outside the page scope
- Move phoenix socket handling inside the Astarte Client
> Use single application-wide Astarte client

- CHANGELOG.md
- package-lock.json
- package.json
- src/elm/Main.elm
- src/elm/Page/Login.elm
- src/elm/Ports.elm
- src/static/index.js
Check if provided token is a valid Astarte authorization token
> Add login form validation

- CHANGELOG.md
- package-lock.json
- package.json
Bump version number and update changelog file.
> Prepare 0.11.1 release

- CHANGELOG.md
- src/elm/Main.elm
- src/elm/Page/TriggerBuilder.elm
- src/elm/Types/Trigger.elm
- src/elm/Types/TriggerAction.elm
- src/elm/Ui/TriggerActionEditor.elm
Implement AQMP trigger action editing in the trigger builder page
> Add AMQP trigger actions

- src/elm/Page/Device.elm
- src/elm/Ui/Card.elm
Show headers in device page cards
> Device page cards with headers

- src/elm/Main.elm
Move realm settings link near the api status sidebar section
> Main.elm: Move realm settings sidebar link

- src/elm/Page/InterfaceBuilder.elm
- src/elm/Page/TriggerBuilder.elm
- src/react/GroupDevicesPage.js
remove resource names from the title, move it to the subtitle if
necessary.
> Page titles and subtitles

- CHANGELOG.md
- src/elm/Icons.elm
- src/elm/Page/Device.elm
- src/elm/Types/DeviceEvent.elm
- src/static/index.js
Listen for device error in the device live events box
> Add support for device error triggers

- CHANGELOG.md
- package-lock.json
- package.json
Update version number and CHANGELOG.md.
> Prepare 1.0.0-alpha.1

- CHANGELOG.md
Rewrite some changelog entries.
> CHANGELOG.md: improve descriptions

- src/elm/Page/Device.elm
- src/elm/Types/DeviceEvent.elm
"value" in incomming data messages can be an object with
multiple values
> Fix incomming_data device events for object interfaces

- src/elm/Page/TriggerBuilder.elm
- src/elm/Types/TriggerAction.elm
- src/elm/Ui/TriggerActionEditor.elm
Adapt to changes in Astarte API
> Rename custom headers in static headers

- src/elm/Main.elm
Notify browser history about page changes when there is an internal page change.
> Fix browser url on page change

- src/elm/Page/Device.elm
Show alias value being deleted instead of the alias tag
> Device.elm: show alias being deleted

- CHANGELOG.md
- src/react/AstarteClient.js
- src/react/RegisterDevicePage.js
- src/static/styles/main.scss
> Add initial introspection when registering devices

- CHANGELOG.md
- src/elm/Page/TriggerBuilder.elm
Allow underscores in path placeholders
> TriggerBuilder: update placeholder regex

- src/elm/Main.elm
Update auth info when accessing with a login request
> Main.elm: fix re-login route

- src/react/FlowConfigurationPage.js
- src/react/FlowInstancesPage.js
- src/react/GroupDevicesPage.js
- src/react/NewGroupPage.js
- src/react/RealmSettingsPage.js
- src/react/RegisterDevicePage.js
This MR enhances the behavior of the UI when an action is in progress: i.e. when creating/deleting a resource, etc.
It does so by adding visual feedback (spinners) when required to make it clear that the user is supposed to be waiting; the action buttons are also disabled when the related action is already initiated and still pending.
> Add activity indicators

- CHANGELOG.md
- package-lock.json
- package.json
Prepare v0.11.2 and update Elixir version to 1.8.2.
> Bump version number to 0.11.2

- CHANGELOG.md
- package-lock.json
- package.json
- src/elm/Modal/MappingBuilder.elm
- src/elm/Page/InterfaceBuilder.elm
Use seconds instead of milliseconds as expiry measurement unit
> Fix expiry measurement unit

- package-lock.json
- package.json
Update webpack copy plugin and update to newer plugin versions.
> Fix webpack dependency vulnerability

- src/elm/Icons.elm
- src/elm/Main.elm
- src/elm/Route.elm
- src/react/AstarteClient.js
- src/react/BlockSourcePage.js
- src/react/BlocksPage.js
- src/react/FlowInstancesPage.js
- src/react/NewBlockPage.js
- src/react/Router.js
- src/react/models/Block.js
- src/react/models/Model.js
Implement React pages to display, create and delete Blocks.
> Add pages for Blocks

- src/react/ui/CheckableDeviceTable.js
Replace JS classes with react hooks
> CheckableDeviceTable: rewrite using react hooks

- src/react/RegisterDevicePage.js
- src/react/hooks/useRelativeTime.js
> Add alerts to the device registration page

- src/react/AstarteClient.js
- src/react/HomePage.js
- src/react/components/WaitForData.js
- src/react/hooks/useFetch.js
Handle data fetching with custom hooks, tracking the request
status with "ok", "err", "loading".
> Add custom hooks for data fetching

- src/react/DeviceInterfaceValues.js
Show alerts when an unexpected error arises while communicatin with Astarte.
> Add alerts to the Device interface data page

- src/react/DevicesPage.js
Refactor Devices page to use React hooks and functional components instead of class components.
> Move Devices page to hooks

- src/elm/Modal/MappingBuilder.elm
- src/elm/Page/InterfaceBuilder.elm
Give users free typing in the numeric input field.
Replace with 0 when input is not a valid number.
Fix #144
> Improve expiry/ttl fields interaction

- src/react/DevicesPage.jsx
- src/react/GroupsPage.jsx
- src/static/index.js
Use HTML elements for user feeback, avoid using console.log
> Remove remaining console.log

- CHANGELOG.md
- package-lock.json
- package.json
- src/react/NewPipelinePage.jsx
- src/react/components/NativeBlockFactory.jsx
- src/react/components/NativeBlockWidget.jsx
- src/react/components/VisualFlowEditor.jsx
- src/react/models/NativeBlockModel.js
- src/static/styles/flow-editor.scss
- src/static/styles/main.scss
Drag and drop blocks and connect blocks together to build a pipeline
> Initial implementation of pipeline visual editor

- .github/workflows/code-quality.yml
Make the CI fail if the project does not compile successfully
> Add checks for code compilation process

- cypress/integration/register_device_page_test.js
Check that generated device id are valid
> Add device registration tests

- CHANGELOG.md
Signed-off-by: Davide Bettio <davide.bettio@ispirata.com>
> Bump version number to 0.11.3

- src/elm/Page/Device.elm
Add missing "/" when joining path tokens
Fix #177
> Device.elm: fix aggregate path format

- cypress/fixtures/test.astarte.FirstInterface.json
- cypress/fixtures/test.astarte.FirstTrigger.json
- cypress/fixtures/triggers.json
- cypress/integration/interface_builder_test.js
- cypress/integration/interfaces_page_test.js
- cypress/integration/register_device_page_test.js
- cypress/integration/trigger_builder_test.js
- cypress/integration/triggers_page_test.js
Fail tests if interface editor or trigger editor pages load with an error.
> Add basic tests for page loading

- cypress/fixtures/blocks.json
- cypress/fixtures/custom_block.json
- cypress/fixtures/native_block.json
- cypress/integration/block_page_test.js
- cypress/integration/blocks_page_test.js
- cypress/integration/new_block_page_test.js
This PR adds basic tests to check the correct rendering of Blocks pages.
> Add Cypress tests for Blocks page

- cypress/fixtures/devices_detailed.json
- cypress/fixtures/devices_stats.json
- cypress/integration/devices_page_test.js
This PR adds basic UI tests to ensure the Devices page is rendered correctly
> Add Cypress tests for Devices page

- cypress/fixtures/group.first-floor.devices.json
- cypress/fixtures/group.test-devices.devices.json
- cypress/fixtures/groups.json
- cypress/integration/groups_page_test.js
- src/react/GroupsPage.jsx
This PR adds basic checks in Cypress to make sure the Groups page correctly renders the list of Groups.
> Add Cypress tests for Groups page

- .github/workflows/functionality-tests.yml
- cypress/integration/new_pipeline_page_test.js
- cypress/support/index.js
- package.json
- webpack.dev.js
This PR adds basic checks in Cypress to make sure the New Pipeline page correctly handle interactions needed to fill the form and submit a new pipeline
> Add Cypress tests for New Pipeline page

- cypress/integration/devices_page_test.js
- src/react/DevicesPage.jsx
- src/react/astarte/Device.js
- src/react/components/Highlight.jsx
> Filter devices by metadata

- src/react/AlertManager.tsx
- src/react/BlockSourcePage.tsx
- src/react/BlocksPage.tsx
- src/react/NewBlockPage.tsx
- src/react/hooks/useInterval.ts
- src/react/hooks/useRelativeTime.ts
- src/react/types/index.ts
- src/react/types/timestamp.ts
- src/react/types/uuid.ts
- src/react/ui/BackButton.tsx
- src/react/ui/SingleCardPage.tsx
This PR adds Typescript's types to Block pages and related components, building from types defined in Astarte Client
> Add typescript for block pages

- .eslintrc.json
- src/react/components/NativeBlockFactory.tsx
- src/react/components/NativeBlockWidget.tsx
- src/react/components/VisualFlowEditor.tsx
- src/react/models/NativeBlockModel.ts
This PR adds Typescript's types to VisualEditor pages and related components, building from types defined in Astarte Client
> Add typescript for VisualEditor pages

- src/astarte-client/client.ts
- src/react/TriggersPage.tsx
This PR adds Typescript's types to Triggers page.
> Add typescript for Triggers page

- src/astarte-client/client.ts
- src/react/RealmSettingsPage.tsx
- src/react/ui/SingleCardPage.tsx
This PR adds Typescript's types to Realm Settings page.
> Add typescript for Realm Settings page

- src/astarte-client/client.ts
- src/react/InterfacesPage.tsx
This PR adds Typescript's types to Interfaces page.
> Add typescript for Interfaces page

- src/astarte-client/client.ts
- src/astarte-client/index.ts
- src/react/RegisterDevicePage.tsx
This PR adds Typescript's types to Register Device page, building from types defined in Astarte Client
> Add typescript for Register Device page

- src/react/BlocksPage.tsx
> BlocksPage: fix typo

- cypress/integration/interface_builder_test.js
- src/astarte-client/client.ts
- src/elm/Main.elm
- src/react/InterfacePage.tsx
- src/react/Router.jsx
- src/react/components/InterfaceEditor.tsx
- src/react/components/modals/Confirm.tsx
This PR implements the Interface page in React, to show and edit the definition of interfaces.
> Port Interface page from Elm to React

- CHANGELOG.md
- src/elm/Page/TriggerBuilder.elm
Show error feedback on data trigger path when trigger is
ValueChange and path /*
See also https://github.com/astarte-platform/astarte/issues/513
> consider ValueChange triggers on path /* as invalid

- CHANGELOG.md
Update v0.11.4 release data in CHANGELOG.md.
Signed-off-by: Davide Bettio <davide.bettio@ispirata.com>
> Prepare v0.11.4 release

- CHANGELOG.md
- package-lock.json
- package.json
Bump version number and update changelog file.
> Prepare 1.0.0-beta.1 release

- cypress/integration/interface_value_page_test.js
- src/react/DeviceInterfaceValues.jsx
- src/react/ui/BackButton.tsx
Add the missing /edit to the back button href URL
> Fix back button on device interface values page

- .github/workflows/build-compatibility.yml
- .github/workflows/docker-build.yml
- .github/workflows/functionality-tests.yml
Test the build process in different OS and with different node versions
> Test build process in different environments

- cypress/fixtures/config/multiple_auth.json
- cypress/fixtures/config/oauth.json
- cypress/integration/login_test.js
- src/react/LoginPage.tsx
- src/react/Router.jsx
- src/static/index.js
When a OAuth provider URL is configured,
it should not be asked to the user
> Fix OAuth login form

- CHANGELOG.md
- cypress/fixtures/device.json
- cypress/fixtures/device_detailed.json
- cypress/fixtures/devices_detailed.json
- cypress/fixtures/group.first-floor.devices.json
- cypress/fixtures/group.special-characters.devices.json
- cypress/fixtures/group.test-devices.devices.json
- cypress/integration/device_page_test.js
- cypress/integration/devices_page_test.js
- src/astarte-client/models/Device/index.ts
- src/astarte-client/types/dto/device.d.ts
- src/elm/AstarteApi.elm
- src/elm/Page/Device.elm
- src/elm/Types/Device.elm
- src/react/DevicesPage.tsx
Parse device attributes field in place of removed metadata field
> Use device attributes instead of metadata

- CHANGELOG.md
CHANGELOG.md: update v1.0.0-beta.2 relase date.
> Prepare v1.0.0-beta.2

- CHANGELOG.md
- package-lock.json
- package.json
- src/elm/Main.elm
- src/static/index.js
- src/static/styles/main.scss
- webpack.common.js
> Add Astarte Dashboard version in the navigation menu 

- CHANGELOG.md
- cypress/integration/block_page_test.js
- cypress/integration/device_page_test.js
- cypress/integration/flows_page_test.js
- cypress/integration/interface_builder_test.js
- cypress/integration/pipeline_page_test.js
- cypress/integration/trigger_builder_test.js
- src/elm/Modal/AskKeyValue.elm
- src/elm/Modal/AskSingleValue.elm
- src/elm/Modal/MappingBuilder.elm
- src/elm/Modal/SelectGroup.elm
- src/elm/Page/Device.elm
- src/elm/Page/InterfaceBuilder.elm
- src/elm/Page/TriggerBuilder.elm
- src/react/BlockSourcePage.tsx
- src/react/FlowInstancesPage.tsx
- src/react/HomePage.jsx
- src/react/PipelineSourcePage.tsx
This PR focuses on improving titles and strings to be more descriptive and accurate. Involved elements are:
- Modal titles
- Modal confirm buttons
- Buttons that open modals
- Links to documentation pages
> Fix titles and strings for buttons and modals

- src/AlertManager.tsx
- src/App.tsx
- src/BlockSourcePage.tsx
- src/DeviceStatusPage/DeviceLiveEventsCard.tsx
- src/DeviceStatusPage/ExchangedBytesCard.tsx
- src/DeviceStatusPage/index.tsx
- src/DevicesPage.tsx
- src/FlowConfigurationPage.tsx
- src/FlowInstancesPage.tsx
- src/GroupsPage.tsx
- src/InterfacePage.tsx
- src/NewBlockPage.tsx
- src/NewGroupPage.tsx
- src/NewInterfacePage.tsx
- src/NewPipelinePage.tsx
- src/NewTriggerPage.tsx
- src/PipelineSourcePage.tsx
- src/RealmSettingsPage.tsx
- src/RegisterDevicePage.tsx
- src/Sidebar.tsx
- src/TriggerPage.tsx
- src/components/InterfaceEditor.tsx
- src/components/TriggerEditor/SimpleTriggerForm.tsx
- src/components/TriggerEditor/index.tsx
- src/components/VisualFlowEditor.tsx
- src/components/modals/Confirm.tsx
Fix warning relative to imports and momoized methods dependencies
> Fix eslint warning on unused imports and exaustive dependencies

- cypress/integration/device_page_test.js
- src/DeviceStatusPage/DeviceLiveEventsCard.tsx
Add a rendering function for incoming data events
holding an object value
> Handle aggregate interface in live events

- CHANGELOG.md
- README.md
> Prepare 1.0.1 release

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
Signed-off-by: Arnaldo Cesco <arnaldo.cesco@secomind.com>
> Prepare 1.0.4 release

- .github/workflows/functionality-tests.yml
Rename node-version parameter to node_version in functionality-tests.yml
> Rename NodeJS version parameter

- CHANGELOG.md
- package-lock.json
- package.json
- src/AstarteManager.tsx
Added token validation in `loadSession` function to revalidate token when dashboard is reloaded or opened from different tab.
Closes #375
> Implement token validation

- CHANGELOG.md
- src/DeviceStatusPage/ExchangedBytesCard.tsx
- Improve Device stats card to show Total Bytes/Messages value instead of NaN
- Documented the changes in CHANGELOG.md
Closes #384
> Improve Device Stats card

- CHANGELOG.md
- package-lock.json
- package.json
- Update the versions included in package.json and package-lock.json
- Update the CHANGELOG.md file with the date of the release.
> Prepare release v1.1.1

- CHANGELOG.md
- src/DeviceStatusPage/AliasesCard.tsx
- src/DeviceStatusPage/AttributesCard.tsx
- src/DeviceStatusPage/DeviceInfoCard.tsx
- src/DevicesPage.tsx
- src/GroupDevicesPage.tsx
- src/astarte-client/models/Device/index.ts
- src/astarte-client/transforms/device.ts
- src/astarte-client/types/dto/device.d.ts
- src/components/Icon.tsx
Added possibility that user can see ```In deletion``` status for every device 
Added new checkbox filter for ```Deletion in progress``` status 
The status changes to `In deletion` on click ```Delete Device``` button
closes #398
> Add Deletion in progress status for every device

- CHANGELOG.md
- cypress/e2e/interface_builder.cy.js
- src/AstarteManager.tsx
- src/DeviceStatusPage/DeviceLiveEventsCard.tsx
- src/DeviceStatusPage/ExchangedBytesCard.tsx
- src/LoginPage.tsx
- src/Router.tsx
- src/astarte-client/models/Interface/index.ts
- src/astarte-client/types/events/AstarteDeviceErrorEvent.ts
- src/components/InterfaceEditor.tsx
Forward port changes occurred in the release-1.1 branch into master
> Forward port 1.1 into master

- CHANGELOG.md
- cypress/e2e/astarte_client.cy.js
- src/astarte-client/client.test.ts
- src/astarte-client/client.ts
- src/astarte-client/models/Trigger/index.ts
- src/astarte-client/transforms/dataTree.ts
- src/astarte-client/types/interfaceValues.ts
The PR forward-ports the changes occurred in the release-1.1 branch to the master branch.
> Forward port 1.1 to master

- CHANGELOG.md
- README.md
- SECURITY.md
- package-lock.json
- package.json
- src/HomePage.tsx
Bump versions contained in the code from 1.1 to 1.2 or 1.2.0-rc.0 as appropriate.
> Prepare release 1.2.0-rc.0

- src/DeviceInterfaceValues.tsx
Add dropdown to select endpoint type.
Display "true"/"false" options in dropdown when
selected endpoint is of type boolean.
Display the endpoint type in dropdown
> Display endpoint type in dropdown and show true/false for boolean type

- .github/workflows/build-compatibility.yml
- .tool-versions
- cypress/e2e/group_page.cy.js
- cypress/e2e/groups_page.cy.js
- package-lock.json
- src/DeviceStatusPage/GroupsCard.tsx
- src/GroupsPage.tsx
- src/components/TriggerEditor/index.tsx
- tsconfig.json
Update the node version specified in the `.tool-versions` and update dependencies with `npm update`
> Update NodeJS version and dependencies

- CHANGELOG.md
Reference the issue #419 being added to the 1.3 release
> Update changelog with cookies entry

- src/DeviceInterfaceValues.tsx
> Add a date/time selector for datetime values

- src/DeviceInterfaceValues.tsx
- Updated modal to list only the mappings that have a value set.
- Mappings without a value are no longer shown as options for unsetting.
> Display only mappings with set values in unset data modal

- src/DeviceInterfaceValues.tsx
Added disabled attribute to the placeholder option in the endpoint selection dropdown
Added disabled attribute to the placeholder option in the value selection dropdown
> Add disabled attribute to placeholder options in dropdowns

- CHANGELOG.md
- src/components/TriggerEditor/SimpleTriggerForm.tsx
Forward port changes occurred in the release-1.1 branch into the release-1.2 branch.
> Forward port release 1.1 into release 1.2

- CHANGELOG.md
- src/components/TriggerEditor/SimpleTriggerForm.tsx
Forward port changes occurred in the release-1.2 branch into the master branch.
> Forward port release 1.2 into master
