astarte-platform/astarte-dashboard

src/elm/Types/InterfaceMapping.elm

sync the regex with the one used by astarte-core

InterfaceMapping: fix endpoint regex

---

CHANGELOG.md
src/elm/Page/InterfaceBuilder.elm

When creating a new mapping for a datastream interface,
set the explicit_timestamp to true.
Fix #19

InterfaceBuilder.elm: explicit_timestamp default true

---

src/static/index.js

Use room_name as a parameter, not as a literal string

index.js: fix channel template

---

CHANGELOG.md
Dockerfile

nginx version 1.13 is not secure. Switch to the latest 1.x version

Update docker image nginx version

---

CHANGELOG.md
src/elm/Page/InterfaceBuilder.elm

Astarte 0.11 supports server owned aggregate objects Interfaces.
Re-enable the form control.

InterfaceBuilder.elm: enable server owned aggregate objects

---

CHANGELOG.md
src/elm/AstarteApi.elm
src/elm/Main.elm
src/elm/Types/Config.elm
src/static/index.js

Use "base api url" to deduct each component URL.
If a specific component url is present, use that instead of
the generated one.

Deduct components URLs when base API URL is provided

---

src/static/index.js

Use /v1 in AppEngine socket URL

index.js: remove workaround on socket URL

---

src/elm/Page/Device.elm
src/static/styles/main.scss

Black may give the idea something is wrong with the device. Use grey
instead.

Use grey for "never connected" device

---

src/static/index.js

When /v1 enpoints were removed from the JSON config,
they were added only in the Elm side of API handling.
Previous releases were not affected because they supported the
deprecated socket URL
Bug introduced in d1a922c9b20298fc98da4c5e50e5feaae07935ab

index.js: Fix AppEngine endpoint URL

---

src/elm/Page/Home.elm

- Information is uncountable, remove ending s.
- more is unnecessary when coupled with the word detailed.

Fix typos in Home

---

CHANGELOG.md
src/elm/Types/Interface.elm

Set explicit timestamp when changing interface type to datastream

Interface: set explicit timestamp when changing type to datastream

---

src/elm/Page/Device.elm
src/elm/Ports.elm
src/static/index.js

Elm 0.19.1 does not support locale aware Time.Posix to string
conversion, and there are no adopted packages in the Elm ecosystem
that handles locales and formats.
Use Ports to send dates to the JS side and convert them there.

Date locale conversion via JS Ports

---

src/elm/Main.elm
src/elm/Ports.elm
src/static/index.js

When leaving a device page, leave the device room and
stop listening for trigger events.

Leave astarte channels rooms when changing pages

---

CHANGELOG.md
src/elm/Page/Home.elm

Map astarte service API status with the appropriate label

Home: fix service health labels

---

src/elm/Main.elm
src/static/index.js

The dashboard shouldn't make any assumption on the external OAuth session.
Logout should only logout the user from the dashboard.

OAuth logout and re-login

---

src/react/DevicesPage.js

Hide pages with no devices.
This was happening to the last page when the device number is a multiple of the number or devices shown per page.

DevicesPage.js: fix device table pagination

---

src/elm/Types/Interface.elm

When cheking for lowercase interface names, treat hyphens as a valid lowercase character

Interface: consider hyphens as lowercase

---

src/elm/Page/TriggerBuilder.elm

Retrieve the interface data when validating a data trigger from source
Fixes #111

TriggerBuilder: Fix datatrigger validation from source

---

src/react/InterfacesPage.js

Allow the interface name container to span the whole
container length

InterfacesPage: Fix interface name max width

---

src/elm/Types/TriggerAction.elm
src/elm/Ui/TriggerActionEditor.elm

Add encoding/decoding implementation and support
in the trigger builder.
Fix #131

Add ignore_ssl_erros in HTTP trigger actions

---

src/elm/Route.elm
src/react/AstarteClient.js
src/react/GroupsPage.js
src/react/Router.js

Group names can contain characters lik % & / ? wich will interfeere
with the REST URL format if unescaped.
see https://github.com/astarte-platform/astarte/issues/456

Encode group names when used in URLs

---

webpack.prod.js

webpack.prod.js
Fix CopyWebpackPlugin params structure that changed with the new
major version.

Fix build script error

---

CHANGELOG.md
src/elm/Page/Device.elm
src/elm/Types/DeviceEvent.elm

Properly decode null incoming_data events as property unset

Add property unset event support

---

webpack.common.js
webpack.dev.js

Configure webpack to use generated sourcemaps

Fix sourcemap warnings with dev-server

---

cypress/fixtures/config_auth.json
cypress/integration/realm_settings_page_test.js
src/react/RealmSettingsPage.jsx

This PR adds basic functionality tests to ensure the settings page is correctly loaded and the user cannot update the public key with clearly invalid values

Add Cypress tests for Realm Settings page

---

cypress/fixtures/interfaces.json
cypress/integration/device_page_test.js
cypress/integration/devices_page_test.js
cypress/integration/interface_builder_test.js
cypress/integration/interfaces_page_test.js
cypress/integration/register_device_page_test.js
cypress/integration/trigger_builder_test.js
cypress/integration/triggers_page_test.js

This PR focuses on using consistent Cypress fixtures.
In doing so, it:
- reworks fixtures so they can be easily reused
- fixes misleading labels on test cases

Fix inconsistencies in Cypress tests

---

cypress/integration/group_page_test.js

This PR adds basic checks in Cypress to make sure the Group page correctly renders the list of devices for the group.

Add Cypress tests for Group page

---

CHANGELOG.md
cypress/integration/devices_page_test.js
src/react/DevicesPage.jsx

Allow users to filter the device list by connection status and
device id or device name.
Fixes #184, #185

Add device filtering to the devices page

---

cypress/fixtures/pipeline.sample-computation.json
cypress/fixtures/pipeline.test-calculation.json
cypress/fixtures/pipelines.json
cypress/integration/pipelines_page_test.js

This PR adds basic checks in Cypress to make sure the Pipelines page correctly renders the list of pipelines and support the interactions needed to manage them.

Add Cypress tests for Pipelines page

---

cypress/integration/sidebar_test.js

This PR adds basic checks in Cypress to make sure the sidebar is correctly rendered with its elements in the right order.

Add Cypress tests for the sidebar

---

cypress/fixtures/flow.room1-occupation.json
cypress/fixtures/flows.json
cypress/integration/flows_page_test.js

This PR adds basic checks in Cypress to make sure the Flows page correctly renders the list of flows and support the interactions needed to manage them.

Add Cypress tests for Flows page

---

cypress/fixtures/group.first-floor.created.json
cypress/integration/new_group_page.js

This PR adds checks in Cypress to make sure the New Group page correctly handles the basic interactions to create a new group of devices

Add Cypress tests for New Group page

---

cypress/integration/pipeline_page_test.js

This PR adds basic checks in Cypress to make sure the Pipeline page correctly renders the pipeline's details.

Add Cypress tests for Pipeline page

---

cypress/integration/home_page_test.js
src/react/HomePage.jsx

This PR adds basic Cypress tests to check if the homepage renders correctly.
It tests for proper behavior on the homepage cards: API Status, Devices, Interfaces, Triggers.

Add Cypress tests for Home page

---

cypress/integration/flow_page_test.js

This PR adds basic checks in Cypress to make sure the Flow page correctly renders a flow with its details

Add Cypress tests for Flow page

---

cypress/fixtures/pipeline.room-occupation.json
cypress/integration/new_flow_page_test.js
src/react/FlowConfigurationPage.jsx

This PR adds basic checks in Cypress to make sure the New Flow page correctly handles interactions to create a new flow

Add Cypress tests for New Flow creation

---

src/elm/Types/Interface.elm

Interface names are considered good names if they represent a
reverse URL notation with only the last group titlecase.
The interface name may contain symbols too.

Interface.elm: good interface names may contain symbols

---

src/astarte-client/client.ts
src/react/DeviceInterfaceValues.jsx
src/react/DevicesPage.jsx
src/react/FlowDetailsPage.jsx
src/react/FlowInstancesPage.jsx
src/react/GroupDevicesPage.jsx
src/react/GroupsPage.jsx
src/react/HomePage.jsx
src/react/InterfacesPage.jsx
src/react/NewGroupPage.jsx
src/react/PipelineSourcePage.jsx
src/react/PipelinesPage.jsx
src/react/RealmSettingsPage.jsx
src/react/RegisterDevicePage.jsx
src/react/TriggersPage.jsx
src/react/components/WaitForData.ts
src/react/hooks/useFetch.ts

This PR moves the logic needed to parse backend API's results inside the Astarte Client, so that React views won't be concerned about implementation details and will get objects easier to consume.

Move API data handling inside Astarte Client

---

CHANGELOG.md
package-lock.json
package.json
src/elm/Page/Device.elm
src/static/styles/main.scss

By default chrome renders the chart with minimum height,
setting height to 100% makes it expand as much as it is allowed.

main.scss: fix device pie chart on Chrome

---

cypress/integration/device_page_test.js
src/elm/Page/Device.elm

This PR fixes a wrong behavior on the Device page where a wrong modal was shown when clicking on the `Add to existing group` button.
A Cypress test is also added to ensure the correct Groups modal is shown instead.

Open groups modal when adding device to existing group

---

cypress/fixtures/device_detailed.json
cypress/integration/device_page_test.js
cypress/support/index.js
cypress/support/websocket.js
package-lock.json
package.json

This PR adds more specific Cypress tests on supported info and interactions for the Device page, such as:
- managing credentials
- managing aliases
- managing metadata
- managing inclusions in groups
- correct rendering of device stats
- correct handling and displaying of live device messages

Add Cypress tests for interactions in Device page

---

src/astarte-client/client.ts
src/astarte-client/models/Device/index.ts
src/astarte-client/transforms/device.ts
src/astarte-client/transforms/index.ts
src/astarte-client/types/dto/device.d.ts
src/react/DeviceInterfaceValues.tsx

This PR reworks the typescript Device model, clearly separating concerns regarding modeling, validation and encoding/decoding.
This way:
- Encoding/decoding happens inside AstarteClient
- A clean Device model is exposed from AstarteClient, which automatically validates data upon class instantiation
- Optionally expose utility functions from AstarteClient to validate data against the Device model

Enhance Device model type and validation

---

src/astarte-client/client.ts
src/astarte-client/index.ts
src/astarte-client/types/event.ts
src/astarte-client/types/index.ts

This PR adds Typescript types to model system and device messages coming from Astarte's websockets.

Add Typescript types for system and device live messages

---

cypress/integration/device_page_test.js

This PR tweaks existing Cypress tests on the Device page to make sure form Modals can be also confirmed by hitting the Enter key

Add Device page tests to confirm modals with Enter

---

cypress/integration/devices_page_test.js
src/react/DevicesPage.tsx

This PR ensures that the ActiveSince filter in Devices page works correctly when entering a date to search for.
A small fix is added to the filter itself, along with a Cypress test that check its functionality.

Add a Cypress test for active devices filter in Devices page

---

cypress/integration/interface_value_page_test.js
src/astarte-client/client.ts
src/astarte-client/index.ts
src/astarte-client/models/Interface/index.ts
src/astarte-client/models/Mapping/index.ts
src/astarte-client/transforms/dataTree.ts
src/astarte-client/transforms/index.ts
src/astarte-client/types/dataType.ts
src/astarte-client/types/interfaceValues.ts
src/react/DeviceInterfaceValues.tsx

This PR implements an AstarteDataTree data structure to encapsulate interfaces data and provide defined ways to export values from it: in an object or linearized fashion.
This way, returned data values are also preprocessed and labeled with metadata (to highlight data type for instance).
A dedicated API is added to `astarte-client`: `getDeviceDataTree`. The gotcha is that, unless the user provides a completed AstarteDevice and a AstarteDevice, this API needs the client credentials to include a RealmManagement token in addition to the AppEngine token already required by the raw `getDeviceData` API.

Use tree structure to format interfaces data

---

cypress/fixtures/config/flowDisabled.json
cypress/integration/login_test.js
src/elm/Main.elm
src/react/HomePage.jsx
src/react/SessionManager.js

This PR fixes the app's behavior in the case where Flow is disabled in the app's config.
Indeed, that resulted in the app crashing on first login. The fix involves:
- Avoiding to read from flowHealth variable in Homepage when Flow is disabled
- In SessionManager, strictly parsing enable_flow_preview as boolean and making sure to always return a flow_url, so the session passed to the Elm side can be correctly parsed and doesn't trigger a NotLoggedIn state
A Cypress test is also added to ensure the app correctly loads when Flow is disabled and that Flow features are disabled: upon login, the sidebar should be visible without showing links to Flow pages and the Homepage shouldn't report health status for Flow APIs.

Fix app crashing when Flow is disabled in the app's config

---

cypress/integration/block_page_test.js
cypress/integration/pipeline_page_test.js
cypress/integration/register_device_page_test.js
src/react/BlockSourcePage.tsx
src/react/FlowInstancesPage.tsx
src/react/GroupDevicesPage.tsx
src/react/NewPipelinePage.tsx
src/react/PipelineSourcePage.tsx
src/react/RealmSettingsPage.tsx
src/react/RegisterDevicePage.tsx
src/react/components/modals/Confirm.tsx
src/react/components/modals/Form.tsx

This PR adds two Modal components useful to standardize and model two situations:
- the case where a *simple confirmation* should be asked to the user before taking some further action (ConfirmModal)
- the case where some *contextual data* should be asked to the user before taking some further action (FormModal)
The FormModal component supports auto-generating forms from a JSON schema definition.
The ConfirmModal is used to ask the user to confirm deletion of a block or pipeline before proceeding with a destructive action:
https://user-images.githubusercontent.com/60540759/101225610-2d6a5300-3692-11eb-8b77-f40c92ba7156.png
https://user-images.githubusercontent.com/60540759/101225614-30fdda00-3692-11eb-846f-ce8cecc25ce5.png
The two modal components are also reused throughout the app to …

Add Confirm and Form modal components

---

cypress/integration/interface_value_page_test.js
src/elm/Page/Device.elm
src/elm/Ui/TriggerActionEditor.elm
src/react/DeviceInterfaceValues.jsx

This PR adjusts the responsive behavior of tables in both Elm and React views, in order to avoid cutting out data that might be overflowing outside the table constraints.

Fix tables responsiveness

---

cypress/integration/device_page_test.js
src/elm/Main.elm

This PR adds two separate scrolling behaviour for sidebar and content, so that scrolling a page of content won't cause the sidebar to disappear from view.
For greater accessibility, a scrollbar will now be visible for the sidebar too when needed.
Before:
After:

Add independent scrolling behaviors for sidebar and content

---

cypress/integration/device_page_test.js

This PR adds more Cypress tests for the Device page, to ensure live error messages coming from a device are correctly displayed in the page.

Add tests for live error messages in Device page

---

cypress/fixtures/config/custom_urls.json
cypress/integration/login_test.js
src/react/SessionManager.js

This PR fixes a typo in the constructor of SessionManager that prevented correct handling of a custom flow_api_url when supplied in app's config: supplying such url would crash the app.
Along with the fix, a Cypress test is added to ensure that if custom Astarte URLs are supplied in the app's config, they are correctly handled by SessionManager and used by the app.

Fix typo in SessionManager's setup

---

cypress/integration/interface_builder_test.js
src/static/index.js

This PR adds a fix to ensure the app correctly loads as a standalone Interface Editor when no config is supplied.
A Cypress test is added as well to test for such behavior.

Fix app crashing when no config is supplied

---

cypress/integration/device_page_test.js
cypress/integration/group_page_test.js
src/astarte-client/client.ts
src/elm/AstarteApi.elm

make sure percent and slash character are properly encoded in API URLs

Double encode group names in Astarte API URLs

---

cypress/fixtures/test.astarte.NoDefaultsInterface.json
cypress/fixtures/test.astarte.SpecifiedDefaultsInterface.json
cypress/integration/interface_builder_test.js
elm.json
src/elm/Modal/MappingBuilder.elm
src/elm/Page/InterfaceBuilder.elm
src/elm/Types/InterfaceMapping.elm

This PR adds more specific Cypress tests to check correct behavior of the Interface Editor in both the New Interface and Edit Interface pages. The tests include:
- correct displaying of interface properties values
- correct rendering of disabled or readonly values
- making sure a proper confirmation modal is shown upon applying changes
- making sure a Interface Source field can be toggled visible and properly parses an interface definition
- interface mappings can be added, edited, deleted, showing a suitable Mapping Editor modal
Some fixes are also included to correct behavior of the Interface Editor:
- changed ID for the endpoint field of the Mapping Editor, so that the corresponding form label has the same ID and clicking the label correctly focuses the field
- fixed InterfaceEditor so …

Add Cypress interaction tests for the Interface Editor

---

CHANGELOG.md
src/elm/Page/TriggerBuilder.elm

ValueChange, ValueChangeApplied and PathCreated can be used only with properties interfaces.
See also astarte-platform/astarte#507
and astarte-platform/astarte#425

Disable ValueChanged, ValueChangedApplied and PathCreated triggers on datastream interfaces

---

cypress/integration/interface_builder_test.js
src/elm/Main.elm

This PR makes sure a navbar is shown on the side of the page even when the app is loaded in standalone Interface Editor mode.
A Cypress test is added as well to verify such behavior.

Show navbar when in standalone Interface Editor mode

---

CHANGELOG.md
cypress/fixtures/test.astarte.NoDefaultsInterface.json
cypress/fixtures/test.astarte.SpecifiedDefaultsInterface.json
cypress/integration/interface_builder_test.js
elm.json
src/astarte-client/client.ts
src/astarte-client/transforms/interface.ts
src/astarte-client/types/dto/interface.d.ts
src/elm/Main.elm
src/elm/Modal/MappingBuilder.elm
src/elm/Page/InterfaceBuilder.elm
src/elm/Types/InterfaceMapping.elm
src/react/NewInterfacePage.tsx
src/react/Router.jsx
src/react/components/InterfaceEditor.tsx
src/react/components/MappingEditor.tsx
src/static/styles/main.scss

This PR implements the New Interface page in React. In doing so, two form components are also introduced, InterfaceEditor and MappingEditor, providing validation and visual feedback for errors and warnings.

Move New Interface page from Elm to React

---

cypress/integration/device_page_test.js
src/elm/Main.elm
src/elm/Modal/ConfirmModal.elm
src/elm/Page/Device.elm
src/elm/Page/TriggerBuilder.elm
src/elm/Route.elm
src/react/RegisterDevicePage.tsx
src/react/Router.jsx

This PR implements a confirmation modal to be shown in DevicePage upon successful wiping of device's credentials secret, so that a feedback is displayed together with an invite to register the device again. A link is included in the feedback, so that by clicking it the user is redirected to the registration form already filled with the correct device ID.

Invite device registration after wiping credentials in DevicePage

---

CHANGELOG.md
src/elm/Page/TriggerBuilder.elm

Here we fix a couple of typos present in the Trigger Builder component:
- Fix wrong label ">=" for Condition Operator "lessOrEqualTo", so that users are not confused by seeing two ">=" identical options.
- Fix wrong DOM ID "#triggerCondition" for Condition Operator field, so that the field has a unique ID and is more accessible since it now gains focus whenever the user clicks on its label.

Fix typos in Trigger Editor

---

CHANGELOG.md
src/elm/Route.elm
src/react/GroupDevicesPage.js
src/react/GroupsPage.js
src/react/Router.js

This PR changes `/resource/:id` routes to `/resource/:id/edit` to avoid conflicts with `/resource/new` routes when the resource has id = new.
This change affects routes for:
- interfaces: `/interfaces/:name/:major` -> `/interfaces/:name/:major/edit`
- triggers: `/triggers/:name` -> `/triggers/:name/edit`
- devices: `/devices/:id` -> `/devices/:id/edit`
- groups: `/groups/:name` -> `/groups/:name/edit`

Change /resource/:id routes to avoid conflicts with /resource/new

---

src/astarte-client/definitions/blocks/virtual_device_pool.json

This PR fixes the JSON Schema for the block `virtual_device_pool` which listed non existent required properties.

Fix virtual_device_pool's JSON Schema

---

CHANGELOG.md
cypress/integration/block_page_test.js
cypress/integration/blocks_page_test.js
cypress/integration/flow_page_test.js
cypress/integration/flows_page_test.js
cypress/integration/new_block_page_test.js
cypress/integration/new_flow_page_test.js
cypress/integration/new_pipeline_page_test.js
cypress/integration/pipeline_page_test.js
cypress/integration/pipelines_page_test.js
src/elm/Route.elm
src/react/BlocksPage.tsx
src/react/FlowInstancesPage.tsx
src/react/NewBlockPage.tsx
src/react/NewPipelinePage.tsx
src/react/PipelinesPage.tsx
src/react/Router.jsx

This PR changes Flow routes to avoid possible conflicts such as the route to create a pipeline `/pipelines/new` conflicting with the route to show a pipeline `/pipelines/<pipelineId>` when pipelineId = new.
This change affects routes for:
- blocks: `/blocks/<blockId>` -> `/blocks/<blockId>/edit`
- pipelines: `/pipelines/<pipelineId>` -> `/pipelines/<pipelineId>/edit`
- flows:
- `/flows/<flowName>` -> `/flows/<flowName>/edit`
- `/flows/new/<pipelineId>` -> `/flows/new?pipelineId=<pipelineId>`

Change Flow routes to avoid possible conflicting routes

---

CHANGELOG.md
package-lock.json
package.json
src/elm/Page/TriggerBuilder.elm

This PR tweaks the Trigger Editor to enforce IncomingData triggers with `/*` paths and `*` match operator on
datastream object interfaces.
This is a workaround for the issue [astarte-platform/astarte#523](https://github.com/astarte-platform/astarte/issues/523)

Limit triggers type for object interfaces

---

CHANGELOG.md
src/elm/Page/TriggerBuilder.elm
src/elm/Types/DataTrigger.elm

This PR adds options in the TriggerEditor to be able to specify a target device or target group even for data triggers.
This feature corresponds to setting a specific `device_id` or `group_name` in a Trigger's JSON form when its `type` equals `data_trigger`. For more details, see [the documentation](https://docs.astarte-platform.org/1.0/060-triggers.html#data-triggers).

Support target device or group in data triggers

---

src/astarte-client/definitions/blocks/dynamic_virtual_device_pool.json
src/astarte-client/definitions/blocks/virtual_device_pool.json

This PR fixes JSON Schema of blocks with proper values for `database_retention_ttl`, avoiding the property to default to 0 which is invalid.

Fix validation of database_retention_ttl in blocks schema

---

cypress/integration/interfaces_page_test.js
cypress/integration/triggers_page_test.js
src/react/InterfacesPage.tsx
src/react/TriggersPage.tsx

This PR fixes some broken links to interfaces and triggers that redirected to non existent paths.
A couple of Cypress tests are added as well to validate the correct behavior when displaying and following these links.

Fix broken links for triggers and interfaces

---

cypress/fixtures/test.astarte.FirstTrigger.json
cypress/integration/trigger_builder_test.js
src/elm/Page/TriggerBuilder.elm

This PR adds more specific Cypress tests to check correct behavior of the Trigger Editor in both the New Trigger and Edit Trigger pages. The tests include:
- correct displaying of trigger properties values
- correct rendering of disabled or readonly values
- correct parsing and generation of a trigger source
- making sure a Trigger Source field can be toggled visible
- making sure a proper confirmation modal is shown upon trigger deletion
- possibility to add, edit, or delete HTTP and AMQP headers for the trigger action
- check that `amqp_routing_key` does not contain `{` or `}`, which are reserved for future uses
- check that `amqp_exchange` follows the `astarte_events_<realm-name>_<any-allowed-string>` format

Add more specific Cypress tests for the Trigger Builder

---

CHANGELOG.md
package-lock.json
package.json
src/react/LoginPage.tsx

Hide the image column when the screen is not wide enough for a 2 column layout

Fix login layout on small screen devices

---

src/react/DeviceStatusPage/index.tsx
src/react/InterfacePage.tsx

This PR adds `<Empty />` component fallbacks that were still missing for loading errors in Interface page and DeviceStatus page.
Interface page before:
Interface page after:
DeviceStatus page before:
DeviceStatus page after:

Add missing fallbacks for loading errors in pages

---

src/react/components/NativeBlockFactory.tsx
src/react/components/NativeBlockWidget.tsx
src/react/components/VisualFlowEditor.tsx
src/react/models/NativeBlockModel.ts
src/static/styles/flow-editor.scss

This PR adds an icon to visual blocks in Pipeline Editor so that they can be removed without using keyboard input.
Before:
After:

Add Remove icon for Pipeline Editor blocks

---

cypress/integration/devices_page_test.js
src/react/App.tsx
src/react/DeviceStatusPage/AddToGroupModal.tsx
src/react/DeviceStatusPage/AliasesCard.tsx
src/react/DeviceStatusPage/DeviceInfoCard.tsx
src/react/DeviceStatusPage/MetadataCard.tsx
src/react/DevicesPage.tsx
src/react/FlowInstancesPage.tsx
src/react/GroupDevicesPage.tsx
src/react/HomePage.tsx
src/react/InterfacesPage.tsx
src/react/NewGroupPage.tsx
src/react/RegisterDevicePage.tsx
src/react/Sidebar.tsx
src/react/TriggersPage.tsx
src/react/components/Icon.tsx
src/react/components/InterfaceEditor.tsx
src/react/components/NativeBlockWidget.tsx
src/react/components/TriggerEditor/TriggerActionForm.tsx
src/react/ui/BackButton.tsx
src/react/ui/SingleCardPage.tsx
src/static/styles/main.scss

This PR adds a reusable Icon component to improve icon usage:
- details about FontAwesome are extracted away from the codebase
- a well-defined list of icons is now available and type-checked with Typescript
- a single clear way to use Tooltips on icons is provided

Add reusable Icon component

---

cypress/fixtures/test_aggregated_object_interface_linearized_values.json
cypress/fixtures/test_individual_object_interface_linearized_values.json
cypress/fixtures/test_individual_object_interface_path_values.json
cypress/fixtures/test_properties_interface_linearized_values.json
cypress/integration/astarte_client.js
src/astarte-client/client.test.ts
src/astarte-client/client.ts
src/astarte-client/transforms/dataTree.test.ts
src/astarte-client/transforms/dataTree.ts
src/astarte-client/types/interfaceValues.ts

This PR adds support for filter params in astarte-client's `getDeviceData()` and `getDeviceDataTree()`.
Supported params include: `path`, `since`, `sinceAfter`, `to`, `limit`.

Add support for filter params when fetching devices data

---

src/static/styles/flow-editor.scss

Fix overflow issue with the Blocks sidebar menu inside the Pipeline Editor that was not contained within the page boundaries.
Pipeline Editor before:
Pipeline Editor after:

Fix Blocks sidebar menu overflowing Pipeline Editor

---

src/AstarteManager.tsx
src/ConfigManager.tsx
src/DeviceStatusPage/DeviceLiveEventsCard.tsx
src/DeviceStatusPage/PreviousInterfacesCard.tsx
src/HomePage.tsx
src/NewPipelinePage.tsx
src/astarte-charts/providers/connectedDevices.ts
src/astarte-client/client.ts
src/astarte-client/models/Flow/index.ts
src/astarte-client/models/Pipeline/index.ts
src/astarte-client/transforms/device.ts
src/astarte-client/types/dto/index.ts
src/astarte-client/types/dto/trigger.d.ts
src/astarte-client/types/events/AstarteDeviceConnectedEvent.ts
src/astarte-client/types/events/AstarteDeviceDisconnectedEvent.ts
src/astarte-client/types/events/AstarteDeviceErrorEvent.ts
src/astarte-client/types/events/AstarteDeviceEvent.ts
src/astarte-client/types/events/AstarteDeviceIncomingDataEvent.ts
src/astarte-client/types/events/AstarteDeviceUnsetPropertyEvent.ts
src/astarte-client/types/events/index.ts
src/components/InterfaceEditor.tsx
src/components/NativeBlockFactory.tsx
src/components/NativeBlockWidget.tsx
src/components/VisualFlowEditor.tsx
src/components/WaitForData.ts
src/components/modals/Form.tsx
src/hooks/useFetch.ts
src/models/NativeBlockModel.ts
src/types/dashboardConfig.ts

Here are some changes to avoid warnings about:
- variables typed as `any`, where a more specific type should be used instead
- redeclared expressions
- third-party objects with non-camelcase properties

Fix Eslint linting warnings

---

src/astarte-client/models/Token/index.ts

Rename `a_hka` token claims to `a_ha`.

Fix typo a_hka for Housekeeping token claims

---

README.md

Config options to overwrite Astarte API URLs
end with _api_url instead of just _url.
Signed-off-by: Mattia Pavinati <mattia.pavinati@secomind.com>

Fix config options to overwrite Astarte API URLs

---

cypress/integration/trigger_builder_test.js
src/react/TriggersPage.tsx

During a Cypress tests that involves a change of route, i.e. redirecting the user to another page, the check for successful redirection is performed as `cy.get('h2').contains(newPageTitle)`. Such a check is bound to fail since `cy.get('h2')` instantly selects the page title before the router has a chance to actually conclude the route change; then the check `.contains(newPageTitle)` times out since the old title is selected.
The issue is fixed by adding a unique `data-testid` DOM attribute to the page and expecting that ID to become visible before attempting to select the title of the page.

Fix Cypress tests doing flaky checks on route redirection

---

CHANGELOG.md
src/react/DeviceInterfaceValues.jsx

When opening the page to display interface values for a certain device, the app crashes for some kind of data, such as datastream object.
The PR updates the data parsing logic to perform more precise parsing so that object datastream values are correctly handled on each interface path.

Fix crash while parsing values of an Astarte interface

---

CHANGELOG.md
src/react/DevicesPage.tsx

On the Devices page, changing the filter settings would trigger a series of queries to fetch all devices not already loaded when the page is first opened.
However, when the user keeps changing the filters then duplicate series of queries are triggered and would load duplicate devices in parallel.
This PR fixes the issue by ensuring that the queries to fetch all remaining devices are only triggered once: when the filters are first changed.
Closes #341

Fix duplicate devices on filter change

---

cypress/integration/blocks_page_test.js
src/react/BlocksPage.tsx

The tests select all `<button />`s inside cards, and then check if one of them contains the name of the expected block.
However, if the block list is still being fetched, the selection logic will resolve right away with the static card that contains the button to create new blocks; the tests will then fail.
The issue is solved by adding a unique `data-testid` DOM attribute to the card of each block, so that it can be easily and precisely selected by Cypress.

Fix Cypress tests on Blocks that have flaky assertions

---

src/NewTriggerPage.tsx
src/TriggerPage.tsx
src/astarte-client/client.ts
src/astarte-client/models/Trigger/index.ts
src/astarte-client/transforms/trigger.ts
src/astarte-client/types/dto/trigger.d.ts
src/components/TriggerEditor/index.tsx

On Astarte Dashboard, added dropdown for Trigger delivery policy in a Trigger Editor.
In Trigger Editor added functionality for listing existing Trigger delivery policies and adding to a Trigger.
In Trigger Editor added functionality for referencing Trigger delivery policy to a Trigger.
Closes #369 
Fix #373

Support for referencing trigger policies in a Trigger

---

cypress/integration/sidebar_test.js
src/App.tsx
src/NewTriggerDeliveryPolicyPage.tsx
src/Router.tsx
src/TriggerDeliveryPoliciesPage.tsx
src/TriggerDeliveryPolicyPage.tsx
src/astarte-client/client.ts
src/astarte-client/models/Policy/index.ts
src/astarte-client/models/Trigger/index.ts
src/astarte-client/types/dto/index.ts
src/astarte-client/types/dto/trigger.d.ts
src/astarte-client/types/dto/triggerDeliveryPolicy.d.ts
src/components/Icon.tsx
src/components/TriggerDeliveryPolicyEditor.tsx
src/components/TriggerDeliveryPolicyHandler.tsx

On Astarte Dashboard, added a new page for Trigger policies.
On new trigger policies page added functionality for listing and adding new trigger policies.
On new trigger policy editor user can enter name of the policy, can add multiple handlers, set retry times, maximum capacity and message lifetime.
Closes #367 
Closes #368 
Closes #370

Add trigger policy editor

---

CHANGELOG.md
package-lock.json
package.json

Prepare codebase for the 1.1.0-rc.0 release.
- Bump the version in package.json to 1.1.0-rc.0
- Note down occurred changes for the release in CHANGELOG.md

Prepare 1.1.0-rc.0 release

---

CHANGELOG.md
src/DeviceStatusPage/DeviceLiveEventsCard.tsx
src/astarte-client/types/events/AstarteDeviceErrorEvent.ts

- Show error metadata in live events when AstarteDeviceErrorEvent is received. 
- Documented the changes in CHANGELOG.md
Closes #377

Show error metadata

---

CHANGELOG.md
cypress/integration/interface_builder_test.js
src/components/InterfaceEditor.tsx

- Allow removing explicit_timestamp from and existing mapping when minor version is changed.
- Documented the changes in CHANGELOG.md
Closes #387

Allow removing explicit_timestamp

---

CHANGELOG.md
src/astarte-client/models/Interface/index.ts

Validate parametric mappings when they overlap on the last leaf. 
Documented the changes in CHANGELOG.md
Closes #324

Validate parametric mappings

---

CHANGELOG.md
src/DeviceStatusPage/DeviceInfoCard.tsx
src/DeviceStatusPage/index.tsx
src/astarte-client/client.ts

Added possibility to delete device through Astarte Dashboard
closes #397

Add Delete device button into DeviceInfoCard

---

CHANGELOG.md
package-lock.json
package.json
src/astarte-client/models/Trigger/index.ts

The `known_value` field was wrongly discarded by the trigger validation logic since the latter expects the interface definition as an additional argument when validating trigger fields that relate to the interface.
When the interface definition is not provided, the validation defaulted to discarding the `known_value` field.
The issue is fixed by not discarding the field in such cases where the exact field type cannot be retrieved. Instead, the field is just allowed to have several types: i.e. one JSON type between `number`, `string`, or `boolean`.

Fix discarded trigger known value

---

CHANGELOG.md
cypress/integration/astarte_client.js
src/astarte-client/client.test.ts
src/astarte-client/client.ts
src/astarte-client/transforms/dataTree.ts
src/astarte-client/types/interfaceValues.ts

The parsing logic didn't properly support the shape of data the are returned when querying datastream object interfaces that have parametric endpoints.
This is because when the endpoints are parametric, instead of accessing the history of published objects for each endpoint, each endpoint key in the resulting data correspond to a single object, which is the latest snapshot of the values for that endpoint object.
The issue is solved by recognizing both arrays and single instances of object values, which are the objects in the resulting data that contain a `timestamp` key besides the other value keys.
With this change, we also make sure that the timestamps returned by Appengine are indeed of type string as expected: the 'keep_milliseconds' query option is thus removed from API calls to …

Fix data parsing on datastream object interfaces with parametric endpoints

---

CHANGELOG.md
src/App.tsx
src/HomePage.tsx
src/RealmSettingsPage.tsx
src/RegisterDevicePage.tsx
src/Sidebar.tsx
src/astarte-client/client.ts

The PR reports the device registration limit, how many devices can be registered, and why new devices cannot be registered.
- The number of devices and the device registration limit are displayed on the sidebar and on the device stats on the homepage.
- The device registration limit is reported as a read-only field on the Realm Settings page.
- When the device registration limit is reached and the user tries to register a new device, an appropriate feedback message is shown explaining why the registration fails.
Navbar without registration limit:
Navbar with registration limit:
Homepage without registration limit:
Homepage with registration limit:
Realm Settings page without registration limit:
Realm Settings page without registration limit:
Feedback shown when trying to register a new …

Display device registration limit

---

CHANGELOG.md
src/DeviceInterfaceValues.tsx
src/astarte-client/client.ts
src/astarte-client/models/InterfaceValue/index.ts
src/astarte-client/models/Mapping/index.ts
src/astarte-client/models/index.ts
src/astarte-client/transforms/dataTree.test.ts
src/astarte-client/transforms/dataTree.ts

Display form for server-owned interfaces to send data to device.
Screenshots:
- If interface type is `datastream` or `properties` and aggregation is `individual` we first have possibility to choose to which endpoint we want to send data.
- Then we insert value 
- If endpoint have some path parameters, we need to fill them and then send data
- If interface aggregation is `object` we need to fill all input fields that are declared in interface mappings and then send data
closes #417

Send data to server-owned interfaces

---

CHANGELOG.md
src/DeviceStatusPage/ExchangedBytesCard.tsx
src/astarte-charts/react/PieChart/index.tsx

Device Stats table shows only interfaces > 0 exchanged messages
PieChart shows only interfaces > 0 exchanged messages
closes. #428

Adapt Device Stats to exclude interfaces with 0 exchanged messages

---

src/astarte-client/models/Interface/index.ts
src/components/InterfaceEditor.tsx
src/components/MappingEditor.tsx

Explicit timestamp is added and removed from modals and interface, depending on the selected owner, and checked at settings change.
Does not enforce explicit_timestamp for already existing interface or after json manual editing
Partially resolves  https://github.com/astarte-platform/astarte-dashboard/issues/447

Remove ExplicitTimestamp from server owned interface

---

CHANGELOG.md
src/AstarteManager.tsx
src/LoginPage.tsx
src/Router.tsx

When signing in with a token, users are now able to choose whether to use a session cookie (which is discarded when the browser is closed) or a persistent cookie that is kept until it expires or is manually cleared
closes #451

Add "Keep me logged in" functionality to login page

---

CHANGELOG.md
src/DeviceInterfaceValues.tsx
src/astarte-client/client.ts

Added a button to allow users to unset properties
endpoints.
Implemented a new modal specifically for unsetting properties
closes #450

Allow unsetting property endpoints

---

src/DeviceInterfaceValues.tsx

Changed button variant from "danger" to "secondary"

Change button variant

---

CHANGELOG.md
cypress/e2e/sidebar.cy.js
package-lock.json
package.json
src/App.tsx
src/AstarteManager.tsx
src/NewTriggerPage.tsx
src/TriggerPage.tsx
src/astarte-client/client.ts
src/components/TriggerEditor/index.tsx

- Added a function to check if the current Astarte version is compatible with trigger delivery policies.
- Updated the Dashboard components to conditionally render UI elements related to trigger delivery policies based on the version check.
closes. #459

Hide Trigger Delivery Policies if Astarte version is unsupported

---

CHANGELOG.md
cypress/e2e/interface_value_page.cy.js
src/DeviceDataStreamValues.tsx
src/DeviceInterfaceValues.tsx
src/DeviceStatusPage/IntrospectionCard.tsx
src/Router.tsx
src/components/FiltersForm.tsx

Add ```from``` - ```to``` time input fields to filter Interface DataStream data
Screenshot:
When filtering both (```from``` time and ```to``` time) :
https://github.com/astarte-platform/astarte-dashboard/assets/34908857/7e0af2e1-f856-46d5-a809-c0dd839c6a6c
When filtering just from time :
https://github.com/astarte-platform/astarte-dashboard/assets/34908857/1b85bfe7-3e7e-461a-ab2e-814f2d835238
closes. #441

Allow to filter time of Interface Datastream data

---

CHANGELOG.md
cypress/integration/sidebar_test.js
package-lock.json
package.json
src/App.tsx
src/AstarteManager.tsx
src/NewTriggerPage.tsx
src/TriggerPage.tsx
src/astarte-client/client.ts
src/components/TriggerEditor/index.tsx

- Added a function to check if the current Astarte version is compatible with trigger delivery policies.
- Updated the Dashboard components to conditionally render UI elements related to trigger delivery policies based on the version check.
closes #459

Disable trigger delivery policies when unsupported

---

CHANGELOG.md
src/components/TriggerEditor/SimpleTriggerForm.tsx

Simplified floating point values for specifying `known_value` in "incoming data" triggers.
closes #465

Improve floating point input handling for `known_value` in Trigger Editor

---

src/components/TriggerEditor/SimpleTriggerForm.tsx

Added autosuggest on path input field when selected interface name
Implemented auto-suggest functionality for the path input field in the Trigger Editor. This feature provides suggestions for 
available mappings when an interface name is selected
closes #432
Screens:

Trigger Editor: Allow autosuggest on path input field when select interface name

---

CHANGELOG.md
src/DeviceStatusPage/DeviceLiveEventsCard.tsx

Use JSON.stringify for all types of values and not only objects.
This will change the behaviour of all the values shown in the component, now all of them are JSON values (e.g. string with `"`, bolean `false`), before React wouldn't have shown `false`, empty arrays or strings.

fix(DeviceLiveEventsCard): show falsey values

---

src/RegisterDevicePage.tsx
src/astarte-client/client.ts

Implement the option to list installed interfaces in the dropdown
- Introduce the fetchInterfacesInfo method to asynchronously retrieve interface details from the Astarte API, including major and minor version information.
- Update the handleNameChange function to set the interfaceDescriptor based on the selected interface from the dropdown, ensuring accurate data representation.
- Modify the UI to utilize <Form.Select>, providing a more intuitive and user-friendly interface for selecting interfaces.
closes #467

Implement the option to list installed interfaces in the dropdown

---

src/HomePage.tsx
src/astarte-client/client.ts

Added new column ```Version``` for the ```ApiStatusCard``` table that displays API versions for each service on the Home page.
View:

Display API versions of each service on the Home page

---

CHANGELOG.md
cypress/e2e/sidebar.cy.js
src/AstarteManager.tsx
src/DevicesPage.tsx
src/GroupsPage.tsx
src/HomePage.tsx
src/InterfacesPage.tsx
src/RealmSettingsPage.tsx
src/TriggerDeliveryPoliciesPage.tsx
src/TriggersPage.tsx
src/astarte-client/client.ts
src/components/Empty.tsx
src/components/Icon.tsx
src/styles/main.scss

**When logged in with invalid JWT token (```astartectl utils gen-jwt all-realm-apis -k test_private.pem```) :**
**When logged in with valid JWT token (```astartectl utils gen-jwt appengine -k test_private.pem```) :**
**When logged in with valid JWT token (```astartectl utils gen-jwt realmmanagement -k test_private.pem```) :**
closes #485

Display useful feedback for invalid JWT token

---

cypress/e2e/home_page.cy.js
src/AstarteManager.tsx
src/DevicesPage.tsx
src/GroupsPage.tsx
src/HomePage.tsx
src/InterfacesPage.tsx
src/RealmSettingsPage.tsx
src/TriggerDeliveryPoliciesPage.tsx
src/TriggersPage.tsx

This update improves how we fetch API versions by introducing permission checks:  
- Before making requests, the app verifies if the user has the required permissions (`canFetch*`).  
- Prevents unnecessary requests when permissions are missing.  
- Uses fallback mechanisms to fetch versions from either authenticated or unauthenticated endpoints.  
Generated valid/invalid ```appengine``` token:
[Screencast from 2025-02-21 10-13-35.webm](https://github.com/user-attachments/assets/b199aa14-075e-4a63-a5b9-1e6e6a6a7979)
Generated valid/invalid ```all-realm-apis``` token:
[Screencast from 2025-02-21 10-30-19.webm](https://github.com/user-attachments/assets/4861187a-d810-4d88-bb44-cce6f0b74d81)
_The reason the pairing version is showing is a problem on the Astarte side, and the reason it didn't …

Optimize API version fetching with permission checks

---

.github/workflows/build-compatibility.yml
.github/workflows/functionality-tests.yml

Updated the following GitHub Actions to version 4:
- actions/checkout@v4
- actions/setup-node@v4
- actions/cache@v4
Ensures compatibility with the latest improvements and security patches

chore(ci): update GitHub Actions to v4
